version: '3'
services:
  postgres:
    image: postgres:14.2-alpine
    container_name: postgres_container
    command: postgres -p 54321
    volumes:
      - ./postgres:/data/postgres
    env_file:
      - .env
    networks:
      - my-app-network

  redis:
    image: redis:7.2.1-alpine
    command: redis-server
    volumes:
      - ./redis:/data
    networks:
      - my-app-network

  sidekiq:
    depends_on:
      - postgres
      - redis
    build: ./web
    command: bundle exec sidekiq
    volumes:
      - ./web:/rails
      - /rails/tmp
    env_file:
      - .env
    networks:
      - my-app-network

  web:
    depends_on:
      - postgres
      - redis
    build: ./web
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    ports:
      - "3000:3000"
    volumes:
      - ./web:/rails
      - /rails/tmp
      - /rails/db
    env_file:
      - .env
    networks:
      - my-app-network

networks:
  my-app-network:
    driver: bridge
